from enum import unique

from pystagram.components.fields.fields import Fields


@unique
class MeFields(Fields):
    ABOUT = "about"
    BIRTHDAY = "birthday"
    ID = "id"
    AGE_RANGE = "age_range"
    EDUCATION = "education"
    EMAIL = "email"
    FAVORITE_ATHLETES = "favorite_athletes"
    FAVORITE_TEAMS = "favorite_teams"
    FIRST_NAME = "first_name"
    GENDER = "gender"
    HOMETOWN = "hometown"
    ID_FOR_AVATARS = "id_for_avatars"
    INSPIRATIONAL_PEOPLE = "inspirational_people"
    INSTALL_TYPE = "install_type"
    INSTALLED = "installed"
    IS_GUEST_USER = "is_guest_user"
    LANGUAGES = "languages"
    LAST_NAME = "last_name"
    LINK = "link"
    LOCATION = "location"
    MEETING_FOR = "meeting_for"
    MIDDLE_NAME = "middle_name"
    NAME = "name"
    NAME_FORMAT = "name_format"
    PAYMENT_PRICEPOINTS = "payment_pricepoints"
    POLITICAL = "political"
    PROFILE_PIC = "profile_pic"
    QUOTES = "quotes"
    RELATIONSHIP_STATUS = "relationship_status"
    SHARED_LOGIN_UPGRADE_REQUIRED_BY = "shared_login_upgrade_required_by"
    SHORT_NAME = "short_name"
    SIGNIFICANT_OTHER = "significant_other"
    SPORTS = "sports"
    SUPPORTS_DONATE_BUTTON_IN_LIVE_VIDEO = "supports_donate_button_in_live_video"
    TOKEN_FOR_BUSINESS = "token_for_business"
    VIDEO_UPLOAD_LIMITS = "video_upload_limits"
    WEBSITE = "website"
    ALBUMS = "albums"
    APPREQUESTFORMERRECIPIENTS = "apprequestformerrecipients"
    APPREQUESTS = "apprequests"
    BUSINESS_USERS = "business_users"
    BUSINESSES = "businesses"
    CONVERSATIONS = "conversations"
    ACCOUNTS = "accounts"
    AD_STUDIES = "ad_studies"
    ADACCOUNTS = "adaccounts"
    ASSIGNED_AD_ACCOUNTS = "assigned_ad_accounts"
    ASSIGNED_BUSINESS_ASSET_GROUPS = "assigned_business_asset_groups"
    ASSIGNED_PAGES = "assigned_pages"
    ASSIGNED_PRODUCT_CATALOGS = "assigned_product_catalogs"
    CUSTOM_LABELS = "custom_labels"
    EVENTS = "events"
    FEED = "feed"
    FRIENDS = "friends"
    FUNDRAISERS = "fundraisers"
    GROUPS = "groups"
    IDS_FOR_APPS = "ids_for_apps"
    IDS_FOR_BUSINESS = "ids_for_business"
    IDS_FOR_PAGES = "ids_for_pages"
    LIKES = "likes"
    LIVE_VIDEOS = "live_videos"
    MUSIC = "music"
    PAYMENT_SUBSCRIPTIONS = "payment.subscriptions"
    PAYMENT_TRANSACTIONS = "payment_transactions"
    PERMISSIONS = "permissions"
    PERSONAL_AD_ACCOUNTS = "personal_ad_accounts"
    PHOTOS = "photos"
    PICTURE = "picture"
    POSTS = "posts"
    RICH_MEDIA_DOCUMENTS = "rich_media_documents"
    VIDEOS = "videos"
