on:
  workflow_call:

jobs:
  github-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
    - name: "Download all the dists ⬇️"
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: "Publish distribution to GitHub releases 🚀"
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          dist/*
